server:
  port: 8080
  tomcat:
    max-threads: 200
    min-spare-threads: 10

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always

spring:
  application:
    name: destiny-online

# 腾讯云生产环境配置
logging:
  level:
    com.destiny: INFO
    org.springframework.web: INFO
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: /home/lighthouse/logs/destiny-online.log
    max-size: 10MB
    max-history: 10